name: Build and deploy Node.js app to Azure Web App - breach-guard-eci

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: { node-version: '22.x' }

      - name: Install all deps
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Install production deps only
        run: npm ci --only=production

      - name: Package for Azure
        run: |
          # Incluye dist, node_modules/serve, package.json y package-lock.json
          zip -r release.zip \
             dist \
             node_modules/serve \
             package.json \
             package-lock.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with: { name: node-app }
      - id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'breach-guard-eci'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_… }}
