# Docs: https://github.com/Azure/webapps-deploy
name: Build and deploy Node.js app to Azure Web App - breach-guard-eci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Clean npm cache and node_modules
        run: |
          npm cache clean --force
          rm -rf node_modules

      - name: Install, build & test
        run: |
          npm install --force
          npm rebuild lightningcss --platform=linux --arch=x64
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          # Empaqueta sólo archivos de proyecto, excluyendo node_modules y .git
          zip -r release.zip . -x "node_modules/*" ".git/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'breach-guard-eci'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8329DCE6762D4D98880304DDB3930D8E }}
